name: hypertrack_plugin
description: Flutter plugin for HyperTrack SDK
version: 0.2.0
homepage: https://www.hypertrack.com/

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.hypertrack.sdk.flutter
        pluginClass: HyperTrackPlugin
      ios:
        pluginClass: HyperTrackPlugin
