name: hypertrack_plugin
description: A wrapper around HyperTrack SDK to make it easier to use in Flutter.
version: 0.1.8
homepage: https://www.hypertrack.com/

environment:
  sdk: ">=2.1.0 <3.0.0"
  flutter: ">=1.10.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.hypertrack.sdk.flutter
        pluginClass: HyperTrackPlugin
      ios:
        pluginClass: HyperTrackPlugin
